
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtsecurity3
    username: root
    password: 112233

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


    hibernate:
      ddl-auto: create
    show-sql: true